---
- name: Setup DevOps Environment
  hosts: localhost
  become: yes
  vars:
    java_version: "11"
    maven_version: "3.9.4"
    jenkins_version: "2.414.1"
    
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: dist
        
    - name: Install required packages
      apt:
        name:
          - curl
          - wget
          - git
          - unzip
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
        state: present
        
    - name: Install Java 11
      apt:
        name: openjdk-11-jdk
        state: present
        
    - name: Set JAVA_HOME
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"'
        
    - name: Download and install Maven
      unarchive:
        src: "https://archive.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
        dest: /opt
        remote_src: yes
        creates: "/opt/apache-maven-{{ maven_version }}"
        
    - name: Create Maven symlink
      file:
        src: "/opt/apache-maven-{{ maven_version }}"
        dest: /opt/maven
        state: link
        
    - name: Add Maven to PATH
      lineinfile:
        path: /etc/environment
        line: 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/maven/bin"'
        
    - name: Install Docker
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
        
    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
        
    - name: Install Docker Compose
      pip:
        name: docker-compose
        
    - name: Install Jenkins
      shell: |
        wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -
        echo "deb https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list
        apt-get update
        apt-get install -y jenkins
        
    - name: Start and enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes
        
    - name: Install Terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        creates: /usr/local/bin/terraform
        mode: '0755'
        
    - name: Create project directory
      file:
        path: /opt/task-manager-devops
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
